using System;
using System.Collections.Specialized;
using System.Linq;
using System.Windows;
using System.Windows.Controls;

namespace PowerLib.WPF.Tools;

public static class DataGridAttach
{
    #region ApplyDefaultStyle

    public static readonly DependencyProperty ApplyDefaultStyleProperty =
        DependencyProperty.RegisterAttached(
            "ApplyDefaultStyle",
            typeof(bool),
            typeof(DataGridAttach),
            new PropertyMetadata(false, OnApplyDefaultStyleChanged));

    public static void SetApplyDefaultStyle(DependencyObject element, bool value)
        => element.SetValue(ApplyDefaultStyleProperty, value);

    public static bool GetApplyDefaultStyle(DependencyObject element)
        => (bool)element.GetValue(ApplyDefaultStyleProperty);

    private static readonly DependencyProperty IsHookedProperty =
        DependencyProperty.RegisterAttached(
            "IsHooked",
            typeof(bool),
            typeof(DataGridAttach),
            new PropertyMetadata(false));

    private static bool GetIsHooked(DependencyObject element)
        => (bool)element.GetValue(IsHookedProperty);

    private static void SetIsHooked(DependencyObject element, bool value)
        => element.SetValue(IsHookedProperty, value);

    private static void OnApplyDefaultStyleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        DataGrid grid = d as DataGrid;
        if (grid == null)
            return;

        bool enable = e.NewValue is bool && (bool)e.NewValue;

        if (enable)
        {
            if (!GetIsHooked(grid))
            {
                grid.Columns.CollectionChanged += OnColumnsCollectionChanged;
                grid.AutoGeneratedColumns += OnAutoGeneratedColumns;
                grid.Loaded += OnGridLoaded;
                SetIsHooked(grid, true);
            }

            UpdateAllColumnStyles(grid);
        }
        else
        {
            if (GetIsHooked(grid))
            {
                grid.Columns.CollectionChanged -= OnColumnsCollectionChanged;
                grid.AutoGeneratedColumns -= OnAutoGeneratedColumns;
                grid.Loaded -= OnGridLoaded;
                SetIsHooked(grid, false);
            }
        }
    }

    private static void OnGridLoaded(object sender, RoutedEventArgs e)
    {
        DataGrid grid = sender as DataGrid;
        if (grid == null || !GetApplyDefaultStyle(grid))
            return;

        UpdateAllColumnStyles(grid);
    }

    private static void OnAutoGeneratedColumns(object sender, EventArgs e)
    {
        DataGrid grid = sender as DataGrid;
        if (grid == null || !GetApplyDefaultStyle(grid))
            return;

        UpdateAllColumnStyles(grid);
    }

    private static void OnColumnsCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
    {
        DataGrid grid = sender as DataGrid;
        if (grid == null || !GetApplyDefaultStyle(grid))
            return;

        if (e.Action == NotifyCollectionChangedAction.Remove || e.Action == NotifyCollectionChangedAction.Move)
            return;

        UpdateAllColumnStyles(grid);
    }

    #endregion

    #region OverrideExistingColumnStyle

    public static readonly DependencyProperty OverrideExistingColumnStyleProperty =
        DependencyProperty.RegisterAttached(
            "OverrideExistingColumnStyle",
            typeof(bool),
            typeof(DataGridAttach),
            new PropertyMetadata(false, OnAnyStyleChanged));

    public static void SetOverrideExistingColumnStyle(DependencyObject element, bool value)
        => element.SetValue(OverrideExistingColumnStyleProperty, value);

    public static bool GetOverrideExistingColumnStyle(DependencyObject element)
        => (bool)element.GetValue(OverrideExistingColumnStyleProperty);

    #endregion

    #region TextColumnStyle

    public static readonly DependencyProperty TextColumnStyleProperty =
        DependencyProperty.RegisterAttached(
            "TextColumnStyle",
            typeof(Style),
            typeof(DataGridAttach),
            new PropertyMetadata(null, OnAnyStyleChanged));

    public static void SetTextColumnStyle(DependencyObject element, Style value)
        => element.SetValue(TextColumnStyleProperty, value);

    public static Style GetTextColumnStyle(DependencyObject element)
        => (Style)element.GetValue(TextColumnStyleProperty);

    public static readonly DependencyProperty EditingTextColumnStyleProperty =
        DependencyProperty.RegisterAttached(
            "EditingTextColumnStyle",
            typeof(Style),
            typeof(DataGridAttach),
            new PropertyMetadata(null, OnAnyStyleChanged));

    public static void SetEditingTextColumnStyle(DependencyObject element, Style value)
        => element.SetValue(EditingTextColumnStyleProperty, value);

    public static Style GetEditingTextColumnStyle(DependencyObject element)
        => (Style)element.GetValue(EditingTextColumnStyleProperty);

    #endregion

    #region ComboBoxColumnStyle

    public static readonly DependencyProperty ComboBoxColumnStyleProperty =
        DependencyProperty.RegisterAttached(
            "ComboBoxColumnStyle",
            typeof(Style),
            typeof(DataGridAttach),
            new PropertyMetadata(null, OnAnyStyleChanged));

    public static void SetComboBoxColumnStyle(DependencyObject element, Style value)
        => element.SetValue(ComboBoxColumnStyleProperty, value);

    public static Style GetComboBoxColumnStyle(DependencyObject element)
        => (Style)element.GetValue(ComboBoxColumnStyleProperty);

    public static readonly DependencyProperty EditingComboBoxColumnStyleProperty =
        DependencyProperty.RegisterAttached(
            "EditingComboBoxColumnStyle",
            typeof(Style),
            typeof(DataGridAttach),
            new PropertyMetadata(null, OnAnyStyleChanged));

    public static void SetEditingComboBoxColumnStyle(DependencyObject element, Style value)
        => element.SetValue(EditingComboBoxColumnStyleProperty, value);

    public static Style GetEditingComboBoxColumnStyle(DependencyObject element)
        => (Style)element.GetValue(EditingComboBoxColumnStyleProperty);

    #endregion

    #region CheckBoxColumnStyle

    public static readonly DependencyProperty CheckBoxColumnStyleProperty =
        DependencyProperty.RegisterAttached(
            "CheckBoxColumnStyle",
            typeof(Style),
            typeof(DataGridAttach),
            new PropertyMetadata(null, OnAnyStyleChanged));

    public static void SetCheckBoxColumnStyle(DependencyObject element, Style value)
        => element.SetValue(CheckBoxColumnStyleProperty, value);

    public static Style GetCheckBoxColumnStyle(DependencyObject element)
        => (Style)element.GetValue(CheckBoxColumnStyleProperty);

    public static readonly DependencyProperty EditingCheckBoxColumnStyleProperty =
        DependencyProperty.RegisterAttached(
            "EditingCheckBoxColumnStyle",
            typeof(Style),
            typeof(DataGridAttach),
            new PropertyMetadata(null, OnAnyStyleChanged));

    public static void SetEditingCheckBoxColumnStyle(DependencyObject element, Style value)
        => element.SetValue(EditingCheckBoxColumnStyleProperty, value);

    public static Style GetEditingCheckBoxColumnStyle(DependencyObject element)
        => (Style)element.GetValue(EditingCheckBoxColumnStyleProperty);

    #endregion

    private static void OnAnyStyleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is not DataGrid grid || !GetApplyDefaultStyle(grid))
            return;

        UpdateAllColumnStyles(grid);
    }

    private static void UpdateAllColumnStyles(DataGrid grid)
    {
        UpdateTextColumnStyles(grid);
        UpdateComboBoxColumnStyles(grid);
        UpdateCheckBoxColumnStyles(grid);
    }

    private static void UpdateTextColumnStyles(DataGrid grid)
    {
        Style elementStyle = GetTextColumnStyle(grid);
        Style editingStyle = GetEditingTextColumnStyle(grid);
        bool overwrite = GetOverrideExistingColumnStyle(grid);

        if (elementStyle != null)
        {
            foreach (DataGridTextColumn col in grid.Columns.OfType<DataGridTextColumn>())
            {
                if (!overwrite && col.ElementStyle != null && !LooksLikeDefaultColumnStyle(col.ElementStyle))
                    continue;

                col.ElementStyle = elementStyle;
            }
        }

        if (editingStyle != null)
        {
            foreach (DataGridTextColumn col in grid.Columns.OfType<DataGridTextColumn>())
            {
                if (!overwrite && col.EditingElementStyle != null && !LooksLikeDefaultColumnStyle(col.EditingElementStyle))
                    continue;

                col.EditingElementStyle = editingStyle;
            }
        }
    }

    private static void UpdateComboBoxColumnStyles(DataGrid grid)
    {
        Style elementStyle = GetComboBoxColumnStyle(grid);
        Style editingStyle = GetEditingComboBoxColumnStyle(grid);
        bool overwrite = GetOverrideExistingColumnStyle(grid);

        if (elementStyle != null)
        {
            foreach (DataGridComboBoxColumn col in grid.Columns.OfType<DataGridComboBoxColumn>())
            {
                if (!overwrite && col.ElementStyle != null && !LooksLikeDefaultColumnStyle(col.ElementStyle))
                    continue;

                col.ElementStyle = elementStyle;
            }
        }

        if (editingStyle != null)
        {
            foreach (DataGridComboBoxColumn col in grid.Columns.OfType<DataGridComboBoxColumn>())
            {
                if (!overwrite && col.EditingElementStyle != null && !LooksLikeDefaultColumnStyle(col.EditingElementStyle))
                    continue;

                col.EditingElementStyle = editingStyle;
            }
        }
    }

    private static void UpdateCheckBoxColumnStyles(DataGrid grid)
    {
        Style elementStyle = GetCheckBoxColumnStyle(grid);
        Style editingStyle = GetEditingCheckBoxColumnStyle(grid);
        bool overwrite = GetOverrideExistingColumnStyle(grid);

        if (elementStyle != null)
        {
            foreach (DataGridCheckBoxColumn col in grid.Columns.OfType<DataGridCheckBoxColumn>())
            {
                if (!overwrite && col.ElementStyle != null && !LooksLikeDefaultColumnStyle(col.ElementStyle))
                    continue;

                col.ElementStyle = elementStyle;
            }
        }

        if (editingStyle != null)
        {
            foreach (DataGridCheckBoxColumn col in grid.Columns.OfType<DataGridCheckBoxColumn>())
            {
                if (!overwrite && col.EditingElementStyle != null && !LooksLikeDefaultColumnStyle(col.EditingElementStyle))
                    continue;

                col.EditingElementStyle = editingStyle;
            }
        }
    }

    private static bool LooksLikeDefaultColumnStyle(Style style)
    {
        if (style == null)
            return true;

        // 经验判定：默认生成的 Column ElementStyle 往往是 BasedOn=null 且只有少量 Setter
        // 你调试看到的“只有4个Setter”基本就是这种情况
        if (style.BasedOn == null && style.Setters.Count > 0 && style.Setters.Count <= 4)
            return true;

        return false;
    }
}